jessie:
  image: adt-jessie_dnspython3_1.11
  before_script:
    - pip3 install -r tests/requirements.txt
  script:
    - coverage run --source ./ -m unittest -v tests.test_acme_dns_tiny
    - coverage report --include=acme_dns_tiny.py

jessie_backport:
  image: adt-jessie_dnspython3_1.15-bpo
  before_script:
    - pip3 install -r tests/requirements.txt
  script:
    - coverage run --source ./ -m unittest -v tests.test_acme_dns_tiny
    - coverage report --include=acme_dns_tiny.py

